"""rename address

Revision ID: 148654b81320
Revises: 422482d3ecfc
Create Date: 2024-07-02 14:51:29.086241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148654b81320'
down_revision = '422482d3ecfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
