"""rename department

Revision ID: 422482d3ecfc
Revises: dd9a991f5bc6
Create Date: 2024-07-02 14:50:07.246386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422482d3ecfc'
down_revision = 'dd9a991f5bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###